############################
# @author EliasDH Team     #
# @see https://eliasdh.com #
# @since 01/01/2025        #
############################
---
apiVersion: v1
kind: Service
metadata:
  name: eliasdhcom-frontend-service
  namespace: eliasdhcom
spec:
  selector:
    app: eliasdhcom-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 4000
---